server:
  port: 7777

spring:
  activemq:
    broker-url: tcp://123.56.169.57:61616
    user: admin
    password: admin

  jms:
    #\u662F\u5426\u662F \u53D1\u5E03-\u8BA2\u9605
    # false\u5C31\u662F\u961F\u5217
    # true\u5C31\u662F\u4E3B\u9898
    pub-sub-domain: false

queue: springboot-activemq-queue